image: ubuntu:latest
script:
  - set -ex \
	&& for key in \
		7937DFD2AB06298B2293C3187D33FF9D0246406D \
		114F43EE0176B71C7BC219DD50A3051F888C628D \
	; do \
		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
	done
	- curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.gz" \
	&& curl -SLO "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
	&& gpg --verify SHASUMS256.txt.asc \
	&& grep " node-v$NODE_VERSION-linux-x64.tar.gz\$" SHASUMS256.txt.asc | sha256sum -c - \
	&& tar -xzf "node-v$NODE_VERSION-linux-x64.tar.gz" -C /usr/local --strip-components=1 \
	&& rm "node-v$NODE_VERSION-linux-x64.tar.gz" SHASUMS256.txt.asc \
	&& npm install -g npm@"$NPM_VERSION" \
	&& npm cache clear
  - sleep 5
  - sudo apt-get -y install git zip libsqlite3-dev sqlite3 dpkg 1> /dev/null 2> /dev/null
  - sudo apt-get install git nodejs nodejs-legacy npm imagemagick build-essential
  - sudo add-apt-repository ppa:chris-lea/redis-server
  - sudo apt-get update && sudo apt-get dist-upgrade
  - npm install -g express
  - npm -d
  - sudo start redis
  - sleep 10
services:
  - redis
notify:
  webhook:
    urls:
      - https://webhooks.gitter.im/e/738cec25e34bafb2650f
    on_started: false
    on_success: true
    on_failure: true
